add new EO tool sealing-factor
WaCoDiS/javaps-wacodis-backend pull request #11
Opened 2019-11-14 10:16 UTC by aklink

Add new EO tool sealing-factor

Provided:
- config/tools/sealing-factor.yml

ToDo: 
- Adapt new Algorithm SealingFactorAlgorithm, similar to VegetationDensityLaiAlgorithm
- support new input type -mask (similar to trainingdata, just geometry, no class column, will be rasterized internally in EO tool)
- Future: support -mask with RASTER option as well (provided by WCS?)

2019-11-15 09:14 UTC, SebaDro commented
New algorithms should be integrated into the master branch only if there implementation has been completed. So first of all, I suggest to implement and test the _SealingFactorAlgorithm_ based on the provided configuration file within the _feature/eo/sealing-factor_ branch before it can be merged into the master branch.

2019-11-15 09:15 UTC, SebaDro requested changes
New algorithms should be integrated into the master branch only if there implementation has been completed. So first of all, I suggest to implement and test the _SealingFactorAlgorithm_ based on the provided configuration file within the _feature/eo/sealing-factor_ branch before it can be merged into the master branch.

2020-02-25 14:15 UTC, aklink commented
Sollte jetzt final sein

2020-02-26 08:09 UTC, SebaDro approved these changes

2020-02-26 08:11 UTC, merged